#!/usr/bin/env node
// Runs build-brand.js for every brands/<slug>/ directory, then regenerates
// the "Brands" directory listing in the top-level index.html between the
// BRANDS:START/BRANDS:END markers in its #start section — the rest of
// index.html (nav, About, Updates, Security, Accessibility) is the
// standard hand-maintained MarinOS app shell and is left untouched,
// the same way build-brand.js leaves each brand's own assets alone.
//
//   node scripts/build-all.js

const fs = require("fs");
const path = require("path");
const { buildBrand } = require("./build-brand");

const repoRoot = path.join(__dirname, "..");
const brandsDir = path.join(repoRoot, "brands");

function esc(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function main() {
  const slugs = fs
    .readdirSync(brandsDir)
    .filter(
      (entry) =>
        fs.statSync(path.join(brandsDir, entry)).isDirectory() &&
        fs.existsSync(path.join(brandsDir, entry, "brand.json"))
    )
    .sort();

  for (const slug of slugs) buildBrand(slug);

  const cards = slugs
    .map((slug) => {
      const data = JSON.parse(fs.readFileSync(path.join(brandsDir, slug, "brand.json"), "utf8"));
      const preferred = (data.logos?.variants || []).find((v) => v.preferred) || data.logos?.variants?.[0];
      const preview = preferred?.preview;
      return (
        `<article class="app-card directory-card">` +
        (preview
          ? `<img class="brand-card__preview" src="brands/${esc(slug)}/${esc(preview)}" alt="" loading="lazy">`
          : "") +
        `<h3><a href="brands/${esc(slug)}/">${esc(data.brand.name)}</a></h3>` +
        `<p>${esc(data.purpose.summary)}</p>` +
        `</article>`
      );
    })
    .join("\n          ");

  const indexPath = path.join(repoRoot, "index.html");
  const indexHtml = fs.readFileSync(indexPath, "utf8");
  const markerPattern = /<!-- BRANDS:START.*?-->[\s\S]*?<!-- BRANDS:END -->/;
  if (!markerPattern.test(indexHtml)) {
    throw new Error("index.html is missing the BRANDS:START/BRANDS:END markers in its #start section.");
  }
  const replacement =
    `<!-- BRANDS:START — regenerated by scripts/build-all.js from brands/*/brand.json. Do not hand-edit between these markers; add a brand under brands/ instead. -->\n          ${cards}\n          <!-- BRANDS:END -->`;
  fs.writeFileSync(indexPath, indexHtml.replace(markerPattern, replacement));

  console.log(`Built ${slugs.length} brand(s): ${slugs.join(", ")}. Regenerated index.html.`);
}

main();
